version: '3'

services:
  # Development overrides
  app:
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    volumes:
      - .:/var/www/html
      - ./var/log:/var/www/html/var/log
      - ./var/cache:/var/www/html/var/cache
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
###< doctrine/doctrine-bundle ###

